### ISSUE TITLE
Trouble updating list when using drag and drop feature with a nanoflow as source

### ISSUE THREAD

**Issue by tlvanleeuwen** [Itvisors/mendix-ReactDnD#2]
Hi there! I have been trying to set up the drag and drop functionality for setting the sorting of a list using an integer attribute and a nanoflow that rearranges all items.

I use a nanoflow as a datasource to retrieve and sort the items I show, and an OnDrag nanoflow where I change the sorting attribute of these items. In the OnDrag NF  I update the DataDateAdded attribute. The drag and drop functionality is working, however the list is not updated and thus the order within the list is not changed immediately (the sort attribute however has been changed, meaning that the logic is working).

I have discovered that I can only update the list by committing the list items themselves, as this triggers the datasource to update its list of items. This is not desirable, as I would have to rollback this action when a user cancels. Committing the parent dataview would be an option, but does not trigger an update of the datasource of the container where my list items are shown. 

Is there a way I could update the list using nanoflows only and not having to commit my objects in the list?

Thanks in advance for your response!

**Comment by mgroeneweg** [comment]
Hi,

What you experience is the sometimes odd behavior of datasources. Because you update the object(s), they are updated in the client as well but your nanoflow that sorts them is not triggered. This has been a major thorn in my side as well.

BTW it is quite common for drag/drop actions to be persistent: If the user re-orders items, that is saved upon drop. 

Probably the best option is to commit everything after the drop. This also reduces the amount of data that has to be transferred between client and backend.

Please note that updating objects in a nanoflow can be counterproductive as nanoflows have no concept of transaction so each activity is handled separately, with a server roundtrip where necessary. Retrieving stuff over association that is already in the client should be OK though. Use the inspection tools of the browser to check network activity, you might be surprised.

As stated in the documentation, datasource XPaths should somehow connect to the context object and datasource microflows should have the context object as parameter. Same goes for datasource nanoflows.

With regards,

Marcel
